/** @type {import('tailwindcss').Config} */
export default {
          content: [
                    "./index.html",
                    "./src/**/*.{js,ts,jsx,tsx}",
          ],
          theme: {
                    extend: {
                              colors: {
                                        "surface-container-highest": "#e2e2e2",
                                        "surface": "#f9f9f9",
                                        "primary-container": "#2d2d2d",
                                        "on-secondary-fixed": "#241a0e",
                                        "inverse-primary": "#c8c6c6",
                                        "tertiary-container": "#2d2d29",
                                        "surface-bright": "#f9f9f9",
                                        "surface-variant": "#e2e2e2",
                                        "on-secondary-container": "#716252",
                                        "surface-dim": "#dadada",
                                        "on-tertiary-fixed": "#1c1c18",
                                        "on-error": "#ffffff",
                                        "surface-container-lowest": "#ffffff",
                                        "inverse-on-surface": "#f0f1f1",
                                        "primary": "#181919",
                                        "secondary": "#6b5c4c",
                                        "on-primary-fixed": "#1b1c1c",
                                        "inverse-surface": "#2f3131",
                                        "background": "#f9f9f9",
                                        "outline": "#747878",
                                        "on-surface-variant": "#444748",
                                        "on-tertiary-fixed-variant": "#474743",
                                        "on-primary": "#ffffff",
                                        "error-container": "#ffdad6",
                                        "on-surface": "#1a1c1c",
                                        "on-primary-fixed-variant": "#474747",
                                        "tertiary-fixed": "#e5e2dc",
                                        "surface-container": "#eeeeee",
                                        "surface-container-high": "#e8e8e8",
                                        "tertiary": "#181915",
                                        "on-error-container": "#93000a",
                                        "on-background": "#1a1c1c",
                                        "tertiary-fixed-dim": "#c9c6c1",
                                        "on-secondary": "#ffffff",
                                        "error": "#ba1a1a",
                                        "surface-container-low": "#f3f3f4",
                                        "on-secondary-fixed-variant": "#524436",
                                        "surface-tint": "#5f5e5e",
                                        "on-tertiary": "#ffffff",
                                        "secondary-fixed": "#f4dfcb",
                                        "primary-fixed-dim": "#c8c6c6",
                                        "secondary-container": "#f4dfcb",
                                        "on-tertiary-container": "#96948f",
                                        "primary-fixed": "#e4e2e1",
                                        "on-primary-container": "#959494",
                                        "secondary-fixed-dim": "#d7c3b0",
                                        "outline-variant": "#c4c7c7"
                              },
                              spacing: {
                                        "gutter": "32px",
                                        "section-gap": "120px",
                                        "margin-desktop": "80px",
                                        "margin-mobile": "20px",
                                        "unit": "8px"
                              },
                              fontFamily: {
                                        "headline-lg-mobile": ["Bodoni Moda", "serif"],
                                        "headline-lg": ["Bodoni Moda", "serif"],
                                        "headline-md": ["Bodoni Moda", "serif"],
                                        "label-caps": ["Hanken Grotesk", "sans-serif"],
                                        "display-lg": ["Bodoni Moda", "serif"],
                                        "body-md": ["Hanken Grotesk", "sans-serif"],
                                        "body-lg": ["Hanken Grotesk", "sans-serif"]
                              }
                    },
          },
          plugins: [],
}